### ISSUE TITLE
Create ERD for Slothstagram

### ISSUE THREAD

**Issue by Underwaterr** [Cosmic-Binturongs/slothstagram#16]
As a user I should be able to log in and then upload a photo with a caption.
Please create the necessary ERD for this functionality.
It should just be a single picture added to the wiki.

**Comment by NasimAkbor** [comment]
https://github.com/Cosmic-Binturongs/slothstagram/wiki/Entity-Relationship-Diagram

**Comment by Underwaterr** [comment]
This is a good start. Some notes:
- What does FK1 etc mean? It seems like they stand for "Foreign Key", but not every column is a foreign key!
- You have a one-to-many relationship defined, but the foreign key field isn't defined. I'd like to see a "user ID" column for your photo table
- Everything is in CamelCase, but our actual table and column names are going to be in snake_case (note the lowercase letters).
- There is no "int" or "string" data type in PostgreSQL, instead use from Django's [Model Fields](https://docs.djangoproject.com/en/4.0/ref/models/fields/), such as `charField` and include any required properties such as `blank=True` or `max_length`. 

By the end, this diagram should make pretty clear what our Django models will look like.
