### ISSUE TITLE
Research back-end deployment

### ISSUE THREAD

**Issue by Underwaterr** [Cosmic-Binturongs/slothstagram#7]
Deploying to Heroku. Will we need to create a special account for deployment?

**Comment by officecowboy** [comment]
Initial build succeeded for bare bones Django app - https://slothstagram.herokuapp.com/:
<img width="406" alt="Screen Shot 2022-05-02 at 2 15 59 PM" src="https://user-images.githubusercontent.com/74625249/166302405-043b10ed-1922-4538-9f3e-c6e66779e210.png">
And everyone's been added as a collaborator on the project app!
